#!/bin/tcsh

#
# A runscript convenient for submitting a run to a queue.
# Modify for your needs and circumstances.
#

conjSofcFoam -case air

####################################################
##                                                ##
##  usage:  qsub -V -cwd -S /bin/tcsh runscript   ##
##                                                ##
####################################################

